id: A574BA608
title: A Sādhana of Kurukullā from the Tidro Dharma Cycle
type: translation
pechas:
- I05F6E70E
- I0461DC14
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:50:14.069845
  last_modified_at: 2023-01-04 12:50:14.069864
  collections:
  - Khenchen Jigme Phuntsok Series
  - Works of Tibetan Masters
alignment_to_base:
  I05F6E70E/0470: 83C1
  I0461DC14/6B8D: 83C1
